TravelBundle\Entity\Room:
    type: entity
    table: null
    repositoryClass: TravelBundle\Repository\RoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roomNumber:
            type: string
            length: 255
            column: room_number
        capacity:
            type: integer
        book:
            type: integer
    lifecycleCallbacks: {  }
