hotel_index:
    path:     /
    defaults: { _controller: "TravelBundle:Hotel:index" }
    methods:  [GET, POST]

hotel_show:
    path:     /{id}/show
    defaults: { _controller: "TravelBundle:Hotel:show" }
    methods:  GET



