travel_hotel:
    resource: "@TravelBundle/Resources/config/routing/hotel.yml"
    prefix:   /hotel

travel_homepage:
    path:     /travel
    defaults: { _controller: TravelBundle:Default:index }

hotels:
    path:     /hotels
    defaults: { _controller: TravelBundle:Show:result, id: null }