# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6f243f5be74434788911445118e4e35fb402de60a9216ac746948842eeb32c87df1c0283edfd8b320287bf6e0c644c274b5f3f840252c4692caba1e0791dcac

test:
  secret_key_base: c9622e1c201eba027816830418edb897a17614b947079df41f0271058f6448599e90cd64cb7e8deb8e22b805e6dabd729ab51a9ae9f7f5857b57bf699ff54920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
